trigger:
- main

pool:
  name: flm-pool

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: CmdLine@2
  inputs:
    script: 'docker build -t kvreddy9120/azrepo:v1 .'

- task: Docker@2
  inputs:
    containerRegistry: 'docker-connection'
    repository: 'kvreddy9120/azrepo'
    command: 'push'
    tags: 'v1'
